# database.py
COUNTY_URLS = {
    # "BAY": "https://bay.realforeclose.com",
    "ORANGE": "https://www.myorangeclerk.realforeclose.com",
    # "VOLUSIA": "https://www.volusia.realforeclose.com",
    # "DUVAL": "https://www.duval.realforeclose.com",
    # "LEON": "https://www.leon.realforeclose.com",
    # "PASCO": "https://www.pasco.realforeclose.com",
    # "MARION": "https://www.marion.realforeclose.com",
    # "MIAMI-DADE": "https://www.miamidade.realforeclose.com",
    # "BROWARD": "https://www.broward.realforeclose.com",
    # "ESCAMBIA": "https://escambia.realforeclose.com",
    # "HILLSBOROUGH": "https://www.hillsborough.realforeclose.com",
    # "POLK": "https://www.polk.realforeclose.com",
    # "ALACHUA": "https://www.alachua.realforeclose.com",
    # "MARTIN": "https://www.martin.realforeclose.com",
    # "SEMINOLE": "https://seminole.realforeclose.com",
    # "PINELLAS": "https://www.pinellas.realforeclose.com",
    # "ST. LUCIE": "https://stlucie.realforeclose.com",
    # "PALM BEACH": "https://palmbeach.realforeclose.com",
    # "SARASOTA": "https://sarasota.realforeclose.com",
    # "MANATEE": "https://www.manatee.realforeclose.com",
    # "CLAY": "https://www.clay.realforeclose.com",
    # "SANTA ROSA": "https://santarosa.realforeclose.com",
    # "CITRUS": "https://www.citrus.realforeclose.com",
    # "JACKSON": "https://jackson.realforeclose.com",
    # "LEE": "https://www.lee.realforeclose.com",
    # "NASSAU": "https://nassauclerk.realforeclose.com",
    # "PUTNAM": "https://putnam.realforeclose.com",
    # "ST. JOHNS": "https://www.saintjohns.realforeclose.com",
    # "WALTON": "https://www.walton.realforeclose.com",
    # "GULF": "https://gulf.realforeclose.com",
    # "INDIAN RIVER": "https://indian-river.realforeclose.com",
    # "CHARLOTTE": "https://www.charlotte.realforeclose.com",
    # "FLAGLER": "https://flagler.realforeclose.com",
    # "WASHINGTON": "https://washington.realforeclose.com",
    # "OKALOOSA": "https://www.okaloosa.realforeclose.com",
    # "GILCHRIST": "https://gilchrist.realforeclose.com"
}
